noravitkai/DWP-project

config/dbcon.php, public/index.php, sql/setup.sql, sql/testdata.sql
Set up database connection (dbcon.php), schema (setup.sql), and data integration test (testdata.sql, index.php)
=> Add database setup and testing

config/dbcon.php, public/index.php
Updated dbcon.php to establish a PDO connection using a reusable dbCon() function and modified index.php to retrieve movie data using PDO methods.
=> Refactor dbcon.php and index.php to use PDO for database connection

sql/testdata.sql, src/Controllers/AdminController.php, src/Views/admin/admin_dashboard.php, src/Views/admin/admin_login.php
Implemented basic admin login, authentication, and simple admin dashboard, with file path corrections
=> Add basic admin login form with POST action

config/session.php, public/js/dashboard-navigation.js, src/Controllers/AdminController.php, src/Views/admin/admin_dashboard.php, src/Views/admin/admin_login.php
Added initial navigation in admin dashboard and implemented logout with session validation
=> Dashboard navigation and logout functionality

public/js/crud-modals.js, src/Controllers/MovieController.php, src/Models/MovieModel.php, src/Views/admin/admin_dashboard.php, src/Views/admin/admin_login.php
Created MovieModel.php and MovieController.php to manage movie data retrieval, updated the admin dashboard to list movies, and added a preview modal along with JavaScript to handle the preview functionality.
=> Add initial movie listing with preview modal for read functionality

config/admin_session.php, config/session.php, config/user_session.php, src/Views/admin/admin_dashboard.php, src/Views/frontend/home_page.php
Moved session handling and role-based access control into distinct session files.
=> Separate session management logic into dedicated files

sql/setup.sql, sql/testdata.sql
Enhanced database schema by adding some constraints.
=> Add NOT NULL and constraints to database tables for data integrity

public/js/crud-modals.js, sql/setup.sql, sql/testdata.sql, src/Controllers/MovieController.php, src/Models/MovieModel.php, src/Views/admin/admin_dashboard.php
Enabled full create, read, update, and delete functionality for managing actors in movie forms, including scrollable modals for better usability.
=> CRUD for actors assigned to movies

public/js/crud-modals.js, src/Controllers/ScreeningController.php, src/Models/ScreeningModel.php, src/Views/admin/admin_dashboard.php
Added a screenings section to the admin dashboard with full CRUD functionalities. Updated navigation links for the admin, news modals layout, plus server-side form handling.
=> Implement CRUD functionalities for screenings in the dashboard

src/Views/frontend/home_page.php
Added a section for displaying the company's details and contact information (phone number, email address, and opening hours).
=> Implement structured layout for cinema company description

src/Controllers/ScreeningController.php, src/Models/ScreeningModel.php, src/Views/frontend/home_page.php
Implemented a dynamic “Daily Showings” section with a fallback card linking to the movie collection, updated ScreeningModel and ScreeningController to fetch today’s screenings, and added a simple alert card if no movie is scheduled for the current day.
=> Add dynamic daily showings section with no-movies alert

config/env_loader.php, public/js/seat-reservation.js, sql/setup.sql, src/Controllers/PaymentController.php, src/Controllers/ReservationController.php, src/Models/PaymentModel.php, src/Models/ReservationModel.php, src/Views/frontend/cancel_page.php, src/Views/frontend/checkout_page.php, src/Views/frontend/payment_page.php, src/Views/frontend/release_reservation.php, src/Views/frontend/success_page.php
Updated payment-reservation integration, database schema, and implemented JS-based reservation expiry to ensure status management and seat release for canceled reservations.
=>  Enhance reservation and payment handling with expiry logic

package-lock.json, src/Views/frontend/footer.php, src/Views/frontend/home_page.php
Added a contact form within the footer layout with navigation links.
=> Implement contact form and footer design

public/js/crud-modals.js, sql/setup.sql, src/Controllers/ReservationController.php, src/Models/ReservationModel.php, src/Views/admin/admin_dashboard.php
Updated the admin dashboard to fetch reservations with a preview modal, and simplified reservation-related queries by using a view.
=> Add reservation overview to the admin dashboard

src/Models/ScreeningModel.php, src/Views/frontend/seat_reservation.php, src/Views/frontend/single_movie.php
Modified the query to filter screenings based on the current date and time and used NOW() to exclude screenings that have already started. Sanitized the GET parameter (id) in the single movie page and redirected invalid or missing IDs to the home page.
=> Update method in ScreeningModel and sanitize GET parameter (id) in single movie page

src/Views/frontend/cancel_page.php, src/Views/frontend/checkout_page.php, src/Views/frontend/footer.php, src/Views/frontend/frontend_navigation.php, src/Views/frontend/home_page.php, src/Views/frontend/profile_page.php, src/Views/frontend/seat_reservation.php, src/Views/frontend/single_movie.php, src/Views/frontend/single_news.php, src/Views/frontend/success_page.php
Included the navbar and footer components into all frontend pages and updated navigation links to correctly redirect to specific sections on the home page.
=> Integrate navbar and footer across pages on frontend

src/Controllers/ReservationController.php, src/Models/ReservationModel.php, src/Views/frontend/profile_page.php, src/Views/frontend/ticket.php
Implemented a reservations section in the profile, created a ticket.php file for ticket generation, and included necessary methods in the ReservationModel and ReservationController.
=> Add reservations section and ticket functionality on profile page

src/Views/frontend/cancel_page.php, src/Views/frontend/checkout_page.php, src/Views/frontend/single_movie.php, src/Views/frontend/single_news.php, src/Views/frontend/success_page.php
Sanitize GET parameters in mutiple files to ensure proper input handling and safe redirection.
=> Sanitize some GET parameters

src/Views/frontend/frontend_navigation.php, src/Views/frontend/success_page.php, src/Views/frontend/ticket.php
Implemented a Print/Save button on success_page.php that redirects to ticket.php, handling both guest and authenticated users.
=> Implement print/save ticket button for all users

assets/css/styles.css, public/index.php, src/Views/frontend/home_page.php
Added utility class to make entire cards clickable, rounded some corners for consistency, and styled the index page with links.
=> Design improvements and UI refinements

src/Controllers/AdminController.php, src/Controllers/CustomerController.php, src/Views/admin/admin_login.php, src/Views/frontend/profile_page.php, src/Views/frontend/user_login.php, src/Views/frontend/user_signup.php
Added allowed actions, CSRF checks, and secure error handling to AdminController, CustomerController, admin_login, user_signup, and user_login.
=> Enhance security of login and signup
